-- 1. ADICIONA AS COLUNAS FALTANTES NA TABELA USUARIOS (SEM MEXER NO QUE JÁ EXISTE)
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) DEFAULT 'comprador';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pendente';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS carteira_saldo DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS carteira_bloqueado DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS asaas_customer_id VARCHAR(100);

-- 2. CRIA A NOVA TABELA DE COMPRAS PARA O SISTEMA DE FRETE/ESCROW
CREATE TABLE IF NOT EXISTS compras (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artesanato_id UUID REFERENCES artesanatos(id),
  comprador_id UUID REFERENCES usuarios(id),
  vendedor_id UUID REFERENCES usuarios(id),
  valor DECIMAL(10,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'aguardando_pagamento',
  asaas_payment_id VARCHAR(100),
  endereco_entrega TEXT,
  valor_frete DECIMAL(10,2) DEFAULT 0.00,
  criado_em TIMESTAMP DEFAULT NOW()
);

-- 3. DESATIVA A TRAVA DE SEGURANÇA PARA O FLASK CONSEGUIR LER/GRAVAR
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE compras DISABLE ROW LEVEL SECURITY;

-- 4. APROVA AUTOMATICAMENTE OS USUÁRIOS ANTIGOS PARA VOCÊ NÃO PERDER SEU ACESSO
UPDATE usuarios SET status = 'aprovado' WHERE status = 'pendente' OR status IS NULL;
UPDATE usuarios SET tipo = 'vendedor' WHERE is_admin = TRUE;
